const actions = {
  SET_STATE: "produk/SET_STATE",
  SUBSCRIBE_TO_PRODUK: "produk/SUBSCRIBE_TO_PRODUK",
  UNSUBSCRIBE_FROM_PRODUK: "produk/UNSUBSCRIBE_FROM_PRODUK",
  ADD_PRODUK: "produk/ADD_PRODUK",
  BATCH_ADD_PRODUK: "produk/BATCH_ADD_PRODUK",
  UPDATE_PRODUK: "produk/UPDATE_PRODUK",
  GET_JENIS_PRODUK: "produk/GET_JENIS_PRODUK",
  UPDATE_JENIS_PRODUK: "produk/UPDATE_JENIS_PRODUK",
};

export default actions;
